export interface IAutoSuggestProps {
  multiSection?: boolean,
  suggestions?: Array<any>,
  onSuggestionsUpdateRequested?: Function,
  getSuggestionValue?: Function,
  renderSuggestion?: Function,
  inputProps?: any,
  shouldRenderSuggestions?: Function,
  onSuggestionSelected?: Function,
  renderSectionTitle?: Function,
  getSectionSuggestions?: Function,
  focusInputOnSuggestionClick?: boolean,
  theme?: any,
  id?: string,
  inputRef?: Function,
  isFocused?: boolean,
  isCollapsed?: boolean,
  focusedSectionIndex?: number,
  focusedSuggestionIndex?: number,
  valueBeforeUpDown?: string,
  lastAction?: string,
  inputFocused?: Function,
  inputBlurred?: Function,
  inputChanged?: Function,
  updateFocusedSuggestion?: Function,
  revealSuggestions?: Function,
  closeSuggestions?: Function
}