export const pins: string;
export const component: string;
export const container: string;
export const layoutHeading: string;
export const sortableFavouriteContainer: string;
export const sortableItemContent: string;
export const removalButton: string;
export const left: string;
export const complete: string;
